### ISSUE TITLE
Count error on Archivist snippet after PHP 7.2 update

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/Archivist#15]
Line 142: $count = count($resources);

Seems to not be getting the object that it is supposed to be getting. I yields this error:

count(): parameter must be an array or an object that implements countable

It seems that the issue appears when using PHP 7.2

We are using MODX 7.0 and PHP Version  7.2.19

**Comment by getandyjones** [comment]
I have the same issue. I updated my server to PHP7.2, and now the Archivist extra is giving me a 500 error when I click on the link to view archives by Year.

**Error message:**
`[2019-10-16 14:51:25] (ERROR @ /home/site/public_html/core/cache/includes/elements/modsnippet/67.include.cache.php : 142) PHP warning: count(): Parameter must be an array or an object that implements Countable
`

If I changed the PHP version back to V7.0, then it's fine.

I have added it on the Modx Community forums, but no luck with a fix so far:
https://community.modx.com/t/archivist-500-error/1672/4

I am using Modx 2.7.2 and PHP 7.2


Thanks
Andy

**Comment by deJaya** [comment]
This issue now brings up a slightly different error on PHP8:

PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, xPDOIterator given in /home/XXX/XXX/core/cache/includes/elements/modsnippet/37.include.cache.php:142

500 for all pages calling Archivist snippet.

MODX 2.8.2

**Comment by deJaya** [comment]
Line 142 should read:

`$count = count(array($resources));`

This fixed the problem for me.

**Comment by sonicpunk** [comment]
@deJaya Want to make a PR of your fix?

**Comment by deJaya** [comment]
Thanks @sonicpunk - TBH I'm probably getting out of my depth as far as Github is concerned so feel free to add away!

**Comment by Lefthandmedia** [comment]
I made a PR for this
https://github.com/modxcms/Archivist/pull/16

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/after-upgrading-to-3-i-get-error-2022-03-31-1434-error-core-cache-includes-elements-modx-revolution-modsnippet-1-include-cache-php-129-php-warning-count-parameter-must-be-an-array-or-an-object-that-implements/5130/6

**Comment by matdave** [comment]
this has been fixed
