### ISSUE TITLE
Support for PHP 7.1.x

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/Archivist#9]
I've just upgraded a server from PHP 5.6.x to PHP 7.1.

When I click on links generated by Archivist, i'm getting an Error 500 - can anybody confirm compatibility ?

**Comment by 4ntz** [comment]
Same here, Running on 7.1.6 - my Archivist Snippet produces nice links like: `href="blog/?arc_year=2017"` but when I click on it I'm getting an Error 500, too.
Did you solve this, @jonleverrier ?

**Comment by jonleverrier** [comment]
I think this was the fix:
https://github.com/modxcms/Archivist/issues/8

**Comment by 4ntz** [comment]
Yes, that does the trick. Thank you!
If someone comes across this: just add `&where=`[]`` to your [[!getArchives]] call (yes, to the getArchives call, not the Archivist call).
